name = "k6web-gps-relay"
main = "gps-worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "gps.jkhgnl.dpdns.org", custom_domain = true }
]

[[kv_namespaces]]
binding = "GPS_KV"
id = "d9e7abbcf6e44496833cea5d7e6702b8"

[[d1_databases]]
binding = "DB"
database_name = "gps"
database_id = "af8934f2-9993-4aa8-afee-8783e559a84b"
